### ISSUE TITLE
Suit -> Suite?

### ISSUE THREAD

**Issue by komocode** [gangverk/GVUserDefaults#22]
NSUserDefaults has the method *initWithSuiteName*

But GVUserDefaults has *- (NSString *)suitName* (notice: suit and not suite).

Might be confusing?

**Comment by kevinrenskers** [comment]
Oops! Good point, will fix in next release :)

**Comment by Ding-Dang** [comment]
no "synchronize"?

**Comment by kevinrenskers** [comment]
Just call that on NSUserDefaults.
