### ISSUE TITLE
bug:sometime store property failure

### ISSUE THREAD

**Issue by yangyangyyluck** [gangverk/GVUserDefaults#23]
Hi. needs help.
I find sometime store property failure.
my category GVUserDefaults (YOSProperties) has property like this:

@property (nonatomic, weak) NSString *currentLoginID;

when network request success. I save userId in success block:
[GVUserDefaults standardUserDefaults].currentLoginID = model.ID;
It work this time. I can get data from [GVUserDefaults standardUserDefaults].currentLoginID
But reopen my app. It doesn't work. [GVUserDefaults standardUserDefaults].currentLoginID return nil

I replace 
[GVUserDefaults standardUserDefaults].currentLoginID = model.ID;
to
[GVUserDefaults standardUserDefaults].currentLoginID = model.ID;
[[NSUserDefaults standardUserDefaults] synchronize];

It works all the time.
thinks.

**Comment by kevinrenskers** [comment]
When using GVUserDefaults you also need to make sure to synchronize NSUserDefaults, or your changes might not be saved before you quit your app.

**Comment by HYAdonisCoding** [comment]
how to synchronize in project?

**Comment by kevinrenskers** [comment]
[[NSUserDefaults standardUserDefaults] synchronize]

**Comment by wonin** [comment]
How to save object?
